### ISSUE TITLE
Incompatibility with Permanent ChatLogs

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#34]
### Bug description

ik u might not want to fix this but this mod makes it so that the chat logs in [permanent chat logs](https://modrinth.com/mod/permanent-chatlogs) are not useable

### Steps to reproduce

1. download the permanent chat logs mod
2. join up into a server and talk all about
3. leave the server and then go to the main menu
4. when you click on the chat logs button, there is a new chat log there. when you open it your chat messages are not there

### Expected behavior

chat logs shouldn't be corrupting

### Actual behavior

they are corrupting

### Minecraft version

1.20.4

### Mod version

2.2.1

### Other information

It only happens when u have timestamps enabled

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
Sorry, but still, I cannot reproduce and it works pretty fine for me.
By the way, don't blame yourself for giving so much suggestions; you are a good tester, and your issues gave me a bunch of good ideas.

![image](https://github.com/user-attachments/assets/eefd1d0a-aad5-42ec-be99-e287bda6c521)
![image2](https://github.com/user-attachments/assets/8c912ae3-a563-46c8-bc9e-69f93426315e)
_Those strange blocks are because the server I'm playing in uses custom resource packs to display custom icons. It's not actually a problem so just ignore it._

**Comment by AlphaLeoli** [comment]
yeah idk it's working now.. i really wonder what that was bc i was testing for a while and it never worked when the timestamps were on but now it does
