### ISSUE TITLE
Clientside Messages

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#44]
### Motivation

it would be super super helpful with testing regex. I know there is the command chattools has to test regex, but this would be better i think. also, it would let you have responders that respond but clientside. You can also have fake messages to trick your friends.

### Description

command to put clientside text. for example, `/fake &7hi there` would put this clientside:
![image](https://github.com/user-attachments/assets/fe4f2766-67a9-4cba-9129-6a966b456fe8)

It would also be cool if you could input custom hover text, click events, etc. Imagine an annoying message sent by a server or mod that tells you to run a command to enable something. Well now, you can run a responder to /fake a message to make "click here" text that when clicked, will make you run a command

Maybe you can choose between a few modes. Like markdown, minecraft mode (& codes), and json (like tellraw). Or maybe it can be defaulted to one, but allow the other modes. idk

### Other information

Clientcommands and Aristois do this already. Clientcommands doesn't do it very well though, and Aristois is a hack client which i dont wannna install.

**Comment by 70CentsApple** [comment]
Done, you can download the artifacts as always.

The command will be `/chattools send_to_client ...`.
Some notes:
- if you want to use it in a responder, DO NOT FORGET to escape `{}` from being considered as a RegEx group. You can turn them into `\{` and `\}`.
- the texts follow [Raw JSON text format](https://minecraft.wiki/w/Raw_JSON_text_format), as `/tellraw` command does (so that you can add hover events or whatever).
